# Numpy

## 1.  Array
## 2. Type Casting Data
## 3. Matrix
## 4. Copy
## Indexing, Slicing, filter, Element wise Multiply - not matrix multiplication, Matri Multiplication, Square root, Log10, Exponential and looping
## 6. From Function,From Iter, From string
## 7. Find Dimension of Array,size,shape
## 8. Built-in-methods - arange, linspace, zeros, ones, empty, eye, logspace
## 9. Reshape
## 10. Random
## 11. Min Max
## 12. Broadcasting

# 1. Array

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
np.array([6,7,8,9])

array([6, 7, 8, 9])

In [15]:
np.array((6,7,8,9)) #you can either give as list or tuples,it doesnt matter

array([6, 7, 8, 9])

In [5]:
np.array([1,2,'shashank',(5+6j)]) # whene we add string to list the whole data is converted to string

array(['1', '2', 'shashank', '(5+6j)'], dtype='<U11')

## 1D Array

In [6]:
np.array([6,7,8,9])

array([6, 7, 8, 9])

In [9]:
np.array([6,7,8,9],ndmin=1)#using n dimensions ndmin

array([6, 7, 8, 9])

## 2D Array

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.array([1,2,3,4,5,6],ndmin=2) #using n dimensions ndmin

array([[1, 2, 3, 4, 5, 6]])

## 3D Array

In [8]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [11]:
np.array([1,2,3,4,5,6],ndmin=3)#using n dimensions ndmin

array([[[1, 2, 3, 4, 5, 6]]])

In [140]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [141]:
a.shape # This means we have 3 2x2 data in here

(3, 2, 2)

In [143]:
b = np.array([[[1,2],[3,4]],[[9,10],[11,12]]])
b


array([[[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [11, 12]]])

In [144]:
b.shape # This means we have 2 2x2 data in here

(2, 2, 2)

In [145]:
c = np.array([[[1,2,3],[3,4,4]],[[5,6,7],[7,8,7]],[[9,10,9],[11,12,4]]])
c

array([[[ 1,  2,  3],
        [ 3,  4,  4]],

       [[ 5,  6,  7],
        [ 7,  8,  7]],

       [[ 9, 10,  9],
        [11, 12,  4]]])

In [147]:
c.shape # This means we have 3 2x3 data in here

(3, 2, 3)

# 2. Type Casting Data

##  Type casting for all data

In [12]:
np.array([[1,2,3],[4,5,6]],dtype= complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [13]:
np.array([[1,2,3],[4,5,6]],dtype= str)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

### Here we are typecasting all the data, what if we want to have different data for different elements

### Example 1

In [17]:
arr = np.array([(1,2),(4,5)],dtype=[('a','<i2'),('b','<i8')])
# Here 'a' represents 1 & 4 , and 'b' represents 2 & 5
# <i2 represents data type of 'a' to be int16
# <i8 represents data type of 'b' to be int64
# <i4 will represent data type as 'int32'

In [18]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [19]:
type(arr[0][0])

numpy.int16

In [24]:
arr[0][0]

1

In [20]:
type(arr[0][1])

numpy.int64

In [25]:
arr[0][1]

2

In [21]:
type(arr[1][0])

numpy.int16

In [26]:
arr[1][0]

4

In [22]:
type(arr[1][1])

numpy.int64

In [27]:
arr[1][1]

5

### Example 2

In [28]:
arr1 = np.array([(1,2),(4,5)],dtype=[('a',complex),('b','<i8')])
# Here 'a' represents 1 & 4 , and 'b' represents 2 & 5
# complex represents data type of 'a' to be complex
# <i8 represents data type of 'b' to be int64

In [29]:
arr1

array([(1.+0.j, 2), (4.+0.j, 5)], dtype=[('a', '<c16'), ('b', '<i8')])

In [32]:
arr1[0][0]

(1+0j)

In [34]:
type(arr1[0][0])

numpy.complex128

# 3. Matrix

In [35]:
arr = np.array([(1,2),(4,5)])

In [39]:
np.mat(arr)

matrix([[1, 2],
        [4, 5]])

In [40]:
np.mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

# 4. Copy

In [41]:
arr = [[1,2],[3,4]]

### Shallow copy

In [42]:
a = arr# the changes made in original array will affect this

### Deep copy

In [43]:
b = np.copy(arr) # the changes made in original array wont affect this copy

In [44]:
arr[0][0]=67

In [45]:
a # here a value changes according to arr

[[67, 2], [3, 4]]

In [46]:
b # here b value does not change according to arr

array([[1, 2],
       [3, 4]])

# 5. Indexing, Slicing, filter, Element wise Multiply - not matrix multiplication, Matri Multiplication, Square root, Log10, Exponential and looping

In [51]:
arr = np.array([(1,2),(4,5),(6,7),(8,9)])

In [52]:
arr[1:3]

array([[4, 5],
       [6, 7]])

In [53]:
arr[-1]

array([8, 9])

In [54]:
arr[:]

array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
for i in arr:
    print(i)

[1 2]
[4 5]
[6 7]
[8 9]


### indexing and slicing 2d array

In [169]:
b = np.random.randint(4,100,(5,5))
b

array([[31, 74, 39, 21, 48],
       [33,  7, 25, 13, 37],
       [38, 23, 49, 70, 97],
       [53, 95, 95, 27, 93],
       [13, 21, 11, 73, 60]])

In [171]:
b[3:,3:]

array([[27, 93],
       [73, 60]])

In [175]:
b[0:4,1:3]

array([[74, 39],
       [ 7, 25],
       [23, 49],
       [95, 95]])

In [176]:
b[:,[1,3]] #take all the rows and take column 1 and column 3

array([[74, 21],
       [ 7, 13],
       [23, 70],
       [95, 27],
       [21, 73]])

In [178]:
b[:4,[1,3]] #take 4 rows and take column 1 and 3

array([[74, 21],
       [ 7, 13],
       [23, 70],
       [95, 27]])

In [181]:
b[[1,3],[1,2]]

array([ 7, 95])

### Filter

In [182]:
b>10

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [183]:
b[b>10]

array([31, 74, 39, 21, 48, 33, 25, 13, 37, 38, 23, 49, 70, 97, 53, 95, 95,
       27, 93, 13, 21, 11, 73, 60])

### Element wise Multiply - not matrix multiplication

In [184]:
b * b

array([[ 961, 5476, 1521,  441, 2304],
       [1089,   49,  625,  169, 1369],
       [1444,  529, 2401, 4900, 9409],
       [2809, 9025, 9025,  729, 8649],
       [ 169,  441,  121, 5329, 3600]])

In [208]:
arr1 = np.random.randint(1,50,(4,4))
arr2 = np.random.randint(1,100,(4,4))
# Dimension of both array should be same

In [186]:
arr1

array([[ 7, 16, 48, 26],
       [36, 47, 16, 31],
       [40,  2, 44, 15],
       [43, 32, 36, 25]])

In [187]:
arr2

array([[90, 76, 40, 15],
       [16, 11, 68, 15],
       [83, 28, 27, 17],
       [57,  5, 72, 11]])

In [189]:
arr3 = arr1 * arr2
arr3

array([[ 630, 1216, 1920,  390],
       [ 576,  517, 1088,  465],
       [3320,   56, 1188,  255],
       [2451,  160, 2592,  275]])

In [191]:
arr1**2

array([[  49,  256, 2304,  676],
       [1296, 2209,  256,  961],
       [1600,    4, 1936,  225],
       [1849, 1024, 1296,  625]], dtype=int32)

### Matrix Multiplication

In [190]:
arr1@arr2

array([[6352, 2182, 4536, 1447],
       [7087, 3856, 7300, 1858],
       [8139, 4369, 4004, 1543],
       [8795, 4753, 6668, 2012]])

### Square root

In [209]:
np.sqrt(arr1)

array([[6.55743852, 5.        , 3.74165739, 1.        ],
       [5.91607978, 5.56776436, 4.24264069, 1.41421356],
       [6.40312424, 5.        , 4.24264069, 5.74456265],
       [5.47722558, 6.08276253, 6.55743852, 5.19615242]])

### Log10

In [210]:
np.log10(arr1)

array([[1.63346846, 1.39794001, 1.14612804, 0.        ],
       [1.54406804, 1.49136169, 1.25527251, 0.30103   ],
       [1.61278386, 1.39794001, 1.25527251, 1.51851394],
       [1.47712125, 1.56820172, 1.63346846, 1.43136376]])

### Exponential

In [211]:
np.exp(arr1)

array([[4.72783947e+18, 7.20048993e+10, 1.20260428e+06, 2.71828183e+00],
       [1.58601345e+15, 2.90488497e+13, 6.56599691e+07, 7.38905610e+00],
       [6.39843494e+17, 7.20048993e+10, 6.56599691e+07, 2.14643580e+14],
       [1.06864746e+13, 1.17191424e+16, 4.72783947e+18, 5.32048241e+11]])

# 6. From Function,From Iter, From string

### Example 1 Fromfunction

In [56]:
np.fromfunction(lambda i,j: i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

### here wherever i == j in 4x4 matrix it will show up as true, i.e (0,0),(1,1),(2,2),(3,3)

### Example 2

In [62]:
np.fromfunction(lambda i,j: i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

### Example 3 from generator function generate data using fromiter

In [63]:
gen = (i*i for i in range(5)) 

In [64]:
np.fromiter(gen,dtype = int)

array([ 0,  1,  4,  9, 16])

### Example 4

In [65]:
np.fromiter(range(5),dtype = int)

array([0, 1, 2, 3, 4])

### Example 5 from string function generates data from strings using fromstring

In [68]:
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

### Example 6

In [69]:
np.fromstring('122 344 677 86',sep=' ',dtype=complex)

array([122.+0.j, 344.+0.j, 677.+0.j,  86.+0.j])

# 7. Find Dimension of Array,size,shape

In [70]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [72]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [73]:
arr1.ndim # To find dimenson of array

2

In [74]:
arr1.size # number of elements

12

In [75]:
arr1.shape

(3, 4)

In [79]:
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
arr2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [78]:
arr2.shape # this means this has 3 2x2 data in this

(3, 2, 2)

# 8. Built-in-methods - arange,linspace,zeros,ones,empty,eye,logspace

### arange

In [81]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [83]:
np.arange(2.2,7.7)

array([2.2, 3.2, 4.2, 5.2, 6.2, 7.2])

In [86]:
np.arange(0,11,2) # step size of 2

array([ 0,  2,  4,  6,  8, 10])

In [87]:
np.arange(21,11,-2) # in reverse direction

array([21, 19, 17, 15, 13])

### linspace

In [88]:
np.linspace(1,8)

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
       3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
       3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143,
       4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
       5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
       6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
       6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
       7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ])

In [89]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [90]:
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [109]:
np.linspace(2,10,20,endpoint=False) #doesnt not include the endpoint

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6, 6. , 6.4, 6.8,
       7.2, 7.6, 8. , 8.4, 8.8, 9.2, 9.6])

In [110]:
np.linspace([2,10],20,axis=1)

array([[ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
         3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
         5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
         7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
         9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
        11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
        13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
        14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
        16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
        18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ],
       [10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
        11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
        12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
        13.06122449, 13.26530612, 13.46938776, 13.

### Zeros

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [92]:
np.zeros((5,5)) #2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
np.zeros((3,5,6)) #3D

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [99]:
np.zeros((3,5,6))+5

array([[[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]]])

### Ones

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [96]:
np.ones((3,3)) #2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.ones((3,2,2)) #3D 

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [98]:
np.ones((3,2,2))+2

array([[[3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.]]])

### Empty

In [104]:
np.empty((3,5))# generate some random data everytime

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
np.empty((4,5)) # generate some random data everytime

array([[ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053],
       [ 4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368],
       [ 6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684],
       [ 8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ]])

In [107]:
np.empty((5,6))

array([[1.10046198e-311, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [2.59145712e+184, 2.23088298e+180, 8.07007068e+169,
        6.70279231e+170, 5.01163106e+217, 5.49419094e-143],
       [9.80058441e+252, 1.30304358e-142, 2.14027814e+161,
        5.04621383e+180, 4.50618615e-144, 7.79952704e-143],
       [1.39615093e-075, 4.66554037e-062, 4.08674779e-033,
        1.32627722e-047, 1.41529403e+161, 6.00736899e-067],
       [4.09940686e+097, 6.38996566e-067, 4.09405440e+126,
        9.30350598e+199, 3.67152475e-062, 4.06321267e-317]])

### Eye

In [108]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### logspace

In [111]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

# 9. Reshape

In [113]:
a = np.linspace(4,7,40)
a

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [115]:
a.ndim

1

In [116]:
a.shape

(40,)

In [118]:
a.reshape(40,1)  # when multiplied it should be equal to 40

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [117]:
a.reshape(5,8) # when multiplied it should be equal to 40
#2D

array([[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
        4.38461538, 4.46153846, 4.53846154],
       [4.61538462, 4.69230769, 4.76923077, 4.84615385, 4.92307692,
        5.        , 5.07692308, 5.15384615],
       [5.23076923, 5.30769231, 5.38461538, 5.46153846, 5.53846154,
        5.61538462, 5.69230769, 5.76923077],
       [5.84615385, 5.92307692, 6.        , 6.07692308, 6.15384615,
        6.23076923, 6.30769231, 6.38461538],
       [6.46153846, 6.53846154, 6.61538462, 6.69230769, 6.76923077,
        6.84615385, 6.92307692, 7.        ]])

In [119]:
a.reshape(2,1,20) # when multiplied it should be equal to 40
#3D

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [121]:
a.reshape(1,4,10) # when multiplied it should be equal to 40

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [155]:
np.random.randint(5,60,(4,4))

array([[57, 16, 50, 29],
       [26, 40, 16,  9],
       [21, 37, 47, 27],
       [10, 25, 30, 24]])

In [156]:
a = np.random.randint(3,9,(3,3))
a

array([[6, 5, 5],
       [4, 7, 3],
       [8, 5, 7]])

In [157]:
a.reshape(1,9)

array([[6, 5, 5, 4, 7, 3, 8, 5, 7]])

In [158]:
a.reshape(9,1)

array([[6],
       [5],
       [5],
       [4],
       [7],
       [3],
       [8],
       [5],
       [7]])

In [159]:
a.reshape(1,3,3) #3D

array([[[6, 5, 5],
        [4, 7, 3],
        [8, 5, 7]]])

In [160]:
a.reshape(3,3,1) #3D

array([[[6],
        [5],
        [5]],

       [[4],
        [7],
        [3]],

       [[8],
        [5],
        [7]]])

In [161]:
a.reshape(3,-1) 
# Here we can give the first dimiension divisible by 9, i.e we have given 3 here and next we can give any 
# negative number, it will automatically undertsand and choose the number divivisible by 9

array([[6, 5, 5],
       [4, 7, 3],
       [8, 5, 7]])

In [162]:
a.reshape(1,-13434)

array([[6, 5, 5, 4, 7, 3, 8, 5, 7]])

In [163]:
a.reshape(9,-13)

array([[6],
       [5],
       [5],
       [4],
       [7],
       [3],
       [8],
       [5],
       [7]])

# 10. Random

### rand - Create an array of the given shape and populate it with random samples from a "Uniform Distribution" over [0,1]

In [122]:
np.random.rand(5) # create 5 random data

array([0.35019144, 0.46101754, 0.46906427, 0.236145  , 0.55841649])

In [123]:
np.random.rand(5,5)

array([[0.10536422, 0.972718  , 0.588751  , 0.10322081, 0.67023471],
       [0.43715612, 0.64523644, 0.03914492, 0.66875628, 0.78428562],
       [0.33099775, 0.78774134, 0.06236665, 0.81226832, 0.36294711],
       [0.78806319, 0.48360744, 0.6124887 , 0.49716882, 0.86513751],
       [0.47539193, 0.23840377, 0.18289974, 0.25062744, 0.63627077]])

In [124]:
np.random.rand(2,5,5)

array([[[0.22676818, 0.24117707, 0.19267735, 0.04449975, 0.9598822 ],
        [0.19070565, 0.11479444, 0.7824029 , 0.21896099, 0.66630763],
        [0.56536697, 0.98928616, 0.26581934, 0.46125604, 0.15115255],
        [0.75239925, 0.47316072, 0.40808146, 0.52876411, 0.1754616 ],
        [0.09448457, 0.80528362, 0.4696795 , 0.18495994, 0.17239096]],

       [[0.53981749, 0.25553947, 0.62366447, 0.43833498, 0.52410472],
        [0.14190704, 0.66101363, 0.50774428, 0.89045608, 0.04134359],
        [0.87792891, 0.32648857, 0.28304599, 0.97973443, 0.40404088],
        [0.56952494, 0.75608362, 0.24389342, 0.53918645, 0.77319263],
        [0.52999576, 0.80953937, 0.53180613, 0.3047502 , 0.5580157 ]]])

### randn - Return a sample (or samples) from the "Standard Normal Distribution". Unlike rand which is Uniform

In [126]:
np.random.randn(5)

array([-0.95165885, -1.14157141, -1.17846965, -1.05465448,  1.22718916])

In [127]:
np.random.randn(5,5)

array([[ 0.52874762,  0.09493114,  0.60027181, -0.36485003, -1.3767767 ],
       [ 0.58175246,  0.29116085, -1.45343785, -0.68669879,  0.84206876],
       [ 0.43496584,  0.79588387,  0.14969553, -0.45787749,  1.44290582],
       [-1.81899734,  0.33947941, -0.99461523, -0.49930096,  0.63304173],
       [ 3.07960411,  0.60890897,  0.69370267, -0.71355626, -0.11244647]])

In [128]:
np.random.randn(2,5,5)

array([[[ 0.13331147,  1.23822591, -0.51282848,  0.54068885,
         -0.16904545],
        [-0.77017144, -0.26525952, -1.05516697,  1.72457768,
         -0.3353267 ],
        [-2.69908168, -1.44358612, -0.3897955 ,  0.15252312,
         -0.18497685],
        [-0.56875736, -0.53905635, -0.56909197,  0.61580785,
         -0.65232031],
        [ 0.23864243, -1.2826752 ,  1.81815436,  0.45584369,
          0.78861041]],

       [[-0.45492385, -0.66905046, -0.95278164, -0.0303039 ,
         -1.60021282],
        [ 0.74045885, -0.28587402, -0.34918893,  0.11552387,
          0.77536779],
        [ 0.26024636, -1.28733839, -0.42532929,  0.31463153,
          1.90159379],
        [ 0.79677812,  0.01555931, -1.81963533,  0.29380623,
         -0.86586159],
        [ 0.23892611, -0.26977564, -1.33609125,  0.35580135,
         -0.6977907 ]]])

### randint - Return random integers from low (inclusive) to high (exclusive)

In [130]:
np.random.randint(1,100)

90

In [131]:
np.random.randint(1,100,10)

array([45, 52, 67, 15, 44, 16, 35, 91, 32, 72])

In [132]:
np.random.randint(5,60,(4,4))#here it generates a 4x4 matrix with random values from 5-60

array([[53,  9, 36, 50],
       [26, 41, 16, 39],
       [19,  6, 51, 52],
       [16, 10, 51, 32]])

In [149]:
a = np.random.randint(3,9,(3,3))
a

array([[5, 3, 3],
       [4, 4, 4],
       [7, 8, 4]])

In [137]:
a.reshape(1,9)

array([[7, 3, 8, 8, 8, 7, 6, 4, 4]])

In [138]:
a.reshape(9,1)

array([[7],
       [3],
       [8],
       [8],
       [8],
       [7],
       [6],
       [4],
       [4]])

In [139]:
a.reshape(1,3,3) #3D

array([[[7, 3, 8],
        [8, 8, 7],
        [6, 4, 4]]])

In [150]:
a.reshape(3,3,1) #3D

array([[[5],
        [3],
        [3]],

       [[4],
        [4],
        [4]],

       [[7],
        [8],
        [4]]])

In [151]:
a.reshape(3,-1) 
# Here we can give the first dimiension divisible by 9, i.e we have given 3 here and next we can give any 
# negative number, it will automatically undertsand and choose the number divivisible by 9

array([[5, 3, 3],
       [4, 4, 4],
       [7, 8, 4]])

In [152]:
a.reshape(3,-13434)

array([[5, 3, 3],
       [4, 4, 4],
       [7, 8, 4]])

In [153]:
a.reshape(1,-13434)

array([[5, 3, 3, 4, 4, 4, 7, 8, 4]])

In [154]:
a.reshape(9,-13)

array([[5],
       [3],
       [3],
       [4],
       [4],
       [4],
       [7],
       [8],
       [4]])

### seed - The random data generated wont change everytime

In [214]:
np.random.seed(13) #if somebody uses 13 then they will have same random data as us, we can use any number inside seed
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

# 11. Min Max

In [164]:
a = np.random.randint(3,9,(3,3))
a

array([[3, 3, 8],
       [7, 7, 4],
       [3, 7, 7]])

In [165]:
a.max()

8

In [166]:
a.min()

3

# 12. Broadcasting

In [193]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [194]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [195]:
arr + a # row wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [196]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [197]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

### here it will not add (broadcast) as the dimensions does not match

In [199]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [200]:
c.reshape(3,1)

array([[1],
       [2],
       [3]])

In [202]:
arr + c.reshape(3,1) # column wise

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [205]:
d = np.array([[1,2,3]])
d

array([[1, 2, 3]])

In [206]:
d.T # Transpose

array([[1],
       [2],
       [3]])

In [207]:
arr + d.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])